# Use postgres/example user/password credentials
version: '3.1'

# list containers
services:
  #1st container
  my-java-container:
    #specify context and dockerfile name
    build:
      dockerfile: Dockerfile
      # Dockerfile location
      context: .
    ports:
      - 8080:8080
# database container
  db:
    image: postgres:12.4-alpine
    # restart: always
    # enviroment variables
    environment:
      - POSTGRES_DB=employees
      - POSTGRES_PASSWORD=hello1234
   # presistent data
    volumes:
      - ~/datadir:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9090:8080